### ISSUE TITLE
new versions of cmake

### ISSUE THREAD

**Issue by plicease** [PerlGameDev/Alien-CMake#5]
Can we get some updated tarballs for platforms like FreeBSD?  I'm happy to do the actual work and have access to most of the relevant platforms.

@FROGGS : some of the binary tarballs for systems not provided by cmake.org itself are getting quite old.  It looks like you created a number of these yourself and are hosting them on your own website.  Did you do anything special when building them (ie. any configure flags?).

**Comment by FROGGS** [comment]
IIRC I did not even build them. I just host a copy of the original tarballs. So that I have a reliable server to fetch the tarballs from.

Do you need a commit bit and/or pause privileges, or what is your plan?

**Comment by plicease** [comment]
My plan was to try and replicate what ever you had done :)   Since some of the URLs point to cmake.org and some point to your server (and I can't find the binary package hosted on your server anywhere else) I assumed that you had created the ones on your server.

If I am able to create/find working packages can/should we host them on your server?  Or can/should I find somewhere else to host them?

I already have commit on the repo.  I just updated the Linux, Windows and os x links yesterday.  PAUSE permissions would be helpful; I could upload new versions without bothering you.

**Comment by plicease** [comment]
@FROGGS : I did a little poking around and it wasn't simple to create binary packages from source for the platforms where binaries aren't provided by cmake.org.  I will probably take another whack at it at some point in the future, but in the meantime I think it would be useful to get the updated binary packages for the platforms that are directly provided by cmake.org, which I have already committed to this repository.  How about doing a release?  Or giving me the PAUSE privileges so I can do it?

**Comment by FROGGS** [comment]
Quote from PAUSE: `Made PLICEASE primary maintainer of Alien::CMake.`

**Comment by FROGGS** [comment]
You are also an admin here, so you can add new collabs to this repository for example...

**Comment by plicease** [comment]
@FROGGS Thanks!

cc: @Perl5-Alien
